---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)

#df <- read.csv("https://raw.githubusercontent.com/mjdacs/data608/master/module3/data/cleaned-cdc-mortality-1999-2010-2.csv")

df <- cleaned_cdc_mortality_1999_2010_2


head(df)

```
```{r}
dfSlice <- df %>% 
  #filter(ICD.Chapter=='Diseases of the circulatory system') %>% 
  filter(Year==2010) %>% 
  arrange(desc(Crude.Rate))
head(dfSlice)
```

```{r}
ggplot(dfSlice, aes(x = reorder(State, Crude.Rate), y = Crude.Rate)) +
  geom_bar(stat = "identity") +
  coord_flip()

```

```{r}
ny_rate <- df %>% 
  filter(ICD.Chapter=='Diseases of the circulatory system', State=='CA')
  
head(ny_rate)
```
```{r}
ggplot(ny_rate, aes(x = Year, y = Crude.Rate)) +
  geom_line(color="blue") 
  
```

```{r}
natl.avg <- df %>% group_by(ICD.Chapter, Year) %>% 
  summarise(Natl.Avg=100000 / (mean(Population)/mean(Deaths)))

natl.avg
```

```{r}
natl.avg2 <- df %>% 
                  group_by(ICD.Chapter,Year) %>% 
                  summarise(Natl.Avg=100000 / (mean(Population)/mean(Deaths))) 

natl.avg2
```

```{r}
ggplot() +
  geom_line(data = ny_rate, aes(x = Year, y = Crude.Rate), color = "blue") +
 geom_line(data = natl.avg2, aes(x = Year, y = Natl.Avg), color = "orange")
```

