---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr) 
data <- read_csv("http://web.mta.info/developers/data/nyct/turnstile/turnstile_191123.txt") 
```
```{r}
dim(data)
```
```{r}
colnames(data)
```



```{r}
sapply(data, function(x) sum(is.na(x)))
```

```{r}
unique(data$DIVISION)
```
```{r}
df <- data %>% filter(DIVISION %in% c("BMT", "IND", "IRT")) %>% 
  mutate(TIME = as.character(TIME),
        ENTRIES = as.integer(ENTRIES),
        EXITS = as.integer(EXITS))
head(df)
```

```{r}

```

Now that structure is understood, get the head of the data set. The first six rows are displayed to give you a snapshot. 

```{r}
unique(df$TIME)
```
```{r}
df %>% filter(STATION == "ATL AV-BARCLAY")
```


```{r}
# dfdt <- df %>% filter(TIME %in% c("03:00:00", "07:00:00", "11:00:00" ,"15:00:00", "19:00:00", "23:00:00",
#                           "01:00:00", "05:00:00", "09:00:00", "13:00:00", "17:00:00", "21:00:00",
#                           "00:00:00", "04:00:00" ,"08:00:00", "12:00:00", "16:00:00", "20:00:00" ,
#                           "02:00:00" ,"06:00:00" ,"10:00:00", "14:00:00" ,"18:00:00", "22:00:00" ))

# dfdt <- df %>% filter(DATE %in% c("11/16/2019", "11/22/2019"),
#                     TIME %in% c("03:00:00", "23:00:00",
#                                 "01:00:00", "21:00:00",
#                                 "00:00:00", "20:00:00",
#                                 "02:00:00", "22:00:00" ))


dfdt <- df %>%
  filter(
          (DATE == "11/16/2019" & TIME %in% c("00:00:00","01:00:00","02:00:00","03:00:00")) |
          (DATE == "11/22/2019" & TIME %in% c("20:00:00","21:00:00","22:00:00", "23:00:00"))
        )


df_audit1 <- df %>%
  filter(
          (DATE == "11/16/2019" & TIME %in% c("00:00:00")) |
          (DATE == "11/22/2019" & TIME %in% c("20:00:00"))
        )

df_audit2 <- df %>%
  filter(
          (DATE == "11/16/2019" & TIME %in% c("01:00:00")) |
          (DATE == "11/22/2019" & TIME %in% c("21:00:00"))
        )

df_audit3 <- df %>%
  filter(
          (DATE == "11/16/2019" & TIME %in% c("02:00:00")) |
          (DATE == "11/22/2019" & TIME %in% c("22:00:00"))
        )

df_audit4 <- df %>%
  filter(
          (DATE == "11/16/2019" & TIME %in% c("03:00:00")) |
          (DATE == "11/22/2019" & TIME %in% c("23:00:00"))
        )
# 
# dfdt %>% filter(DATE == "11/16/2019" & TIME %in% c("00:00:00",
#                                                   "01:00:00",
#                                                   "02:00:00",
#                                                   "03:00:00") )
dfdt
```
```{r}
df_audit1
```
```{r}
df1 <- df_audit1 %>% 
  mutate(Total_Enter = ENTRIES - lag(ENTRIES, 1),
                Total_Exit = EXITS - lag(EXITS, 1)) %>% 
  filter(Total_Enter > 0 & DATE == "11/22/2019") %>% 
  group_by(STATION) %>% 
  filter(STATION != "ALLERTON AV" & !SCP %in% c("00-00-00"),
         STATION != "125 ST" & !SCP %in% c("00-05-01"),
         STATION != "WTC-CORTLANDT" & !SCP %in% c("00-03-00","03-00-00","03-00-01","03-00-02")) %>% 
  summarise(Week_Total_Entries = sum(Total_Enter),
            Week_Total_Exits = sum(Total_Exit)) %>% 
  arrange(desc(Week_Total_Entries))

df1
```
```{r}
df_audit1 %>% 
  select(SCP, STATION, DATE, TIME, DESC, ENTRIES, EXITS) %>% 
  filter(STATION == "96 ST")
```


```{r}
df_audit2
```
```{r}
df2 <- df_audit2 %>% 
  mutate(Total_Enter = ENTRIES - lag(ENTRIES, 1),
                Total_Exit = EXITS - lag(EXITS, 1)) %>% 
  filter(Total_Enter > 0 & DATE == "11/22/2019") %>% 
  group_by(STATION) %>% 
  summarise(Week_Total_Entries = sum(Total_Enter),
            Week_Total_Exits = sum(Total_Exit)) %>% 
  arrange(desc(Week_Total_Entries))

df2
```


```{r}
df_audit3
```

```{r}
df3 <- df_audit3 %>% 
  mutate(Total_Enter = ENTRIES - lag(ENTRIES, 1),
                Total_Exit = EXITS - lag(EXITS, 1)) %>% 
  filter(Total_Enter > 0 & DATE == "11/22/2019") %>% 
  group_by(STATION) %>% 
  summarise(Week_Total_Entries = sum(Total_Enter),
            Week_Total_Exits = sum(Total_Exit)) %>% 
  arrange(desc(Week_Total_Entries))

df3
```

```{r}
df_audit4 %>% select(STATION, LINENAME) 

```
```{r}
df4 <- df_audit4 %>% 
  mutate(Total_Enter = ENTRIES - lag(ENTRIES, 1),
                Total_Exit = EXITS - lag(EXITS, 1)) %>% 
  filter(Total_Enter > 0 & DATE == "11/22/2019") %>% 
  group_by(STATION) %>%
  filter(STATION != "42 ST-PORT AUTH" & !SCP %in% c("00-00-08", "00-00-09"),
         STATION != "RECTOR ST" & !SCP %in% c("01-03-00", "01-06-00"),
         STATION != "47-50 STS ROCK" & !SCP %in% 
                           c("02-06-00","02-06-01",
                             "02-03-00","02-03-01","02-03-02","02-03-03",
                             "01-03-02",
                             "00-03-00", "00-03-01","00-03-02","00-03-03","00-03-04","00-03-05"),
         STATION != "86 ST" & !SCP %in% 
                            c("00-00-00", "00-00-01", "00-03-00", "00-03-01", "00-03-02")
         ) %>%       
  summarise(Week_Total_Entries = sum(Total_Enter),
            Week_Total_Exits = sum(Total_Exit)) %>% 
  arrange(desc(Week_Total_Entries))

df4
```
```{r}
df_audit4 %>% 
  select(SCP, STATION, DATE, TIME, DESC, ENTRIES, EXITS) %>% 
  filter(STATION == "86 ST")
```

```{r}

clean_df <- bind_rows(df1, df2, df3, df4)

total.by.station <- clean_df %>% group_by(STATION) %>% 
  summarise(Week_Total_Entries = sum(Week_Total_Entries),
            Week_Total_Exits = sum(Week_Total_Exits)) %>% 
  arrange(desc(Week_Total_Entries))

```
```{r}
total.by.station
```



```{r}
data_viz <- clean_entr[1:20,] %>% arrange(desc(Week_Total_Entries))
```

```{r message=FALSE, fig.width=8.75}

ggplot(data_viz, aes(x = reorder(STATION, Week_Total_Entries), y = Week_Total_Entries)) +
  geom_bar(stat = "identity", fill = "navy", width = .5) +
  geom_text(aes(label=Week_Total_Entries),
            position=position_dodge(width = 0.1), hjust = -0.03, vjust = 0.5, size = 2.5) +
    coord_flip() +
  scale_y_continuous(labels = scales::comma) +
  theme(text = element_text(size = 10)) +
  labs(title = "The 20 Busiest NYC Subway Stations by Entry",
       subtitle = "One week period 11/16/2019-11/22/2019. Data courtesty of mta.info",
       caption = "mdac",
       x = "Station",
       y = "Entries per station") 
  
ggsave("mdacplot.png")
```
```{r}
data_viz_hi <- head(clean_entr,20) %>% 
  mutate(Total_Traffic = Week_Total_Entries + Week_Total_Exits) %>% 
  select(STATION,Total_Traffic) %>% 
  arrange(desc(Total_Traffic))

data_viz_hi
```
```{r message=FALSE, fig.width=10}
ggplot(data_viz_hi, aes(x = reorder(STATION, Total_Traffic), y = Total_Traffic)) +
  geom_bar(stat = "identity", fill = "navy", width = .5) +
  geom_text(aes(label=Total_Traffic),
            position=position_dodge(width = 0.1), hjust = -0.03, vjust = 0.5, size = 2.5) +
    coord_flip() +
  scale_y_continuous(labels = scales::comma) +
  theme(text = element_text(size = 10)) +
  labs(title = "The 20 Busiest NYC Subway Stations by Total Turnstile Count",
       subtitle = "Total entries and exits for the one week period 11/16/2019-11/22/2019. Data courtesty of mta.info",
       caption = "mdac",
       x = "Station",
       y = "Entries per station") 
  
ggsave("total_hi.png")
```

```{r}
data_viz_low <- tail(clean_df,20) %>% 
  mutate(Total_Traffic = Week_Total_Entries + Week_Total_Exits) %>% 
  select(STATION, Total_Traffic) %>% 
  arrange(Total_Traffic)

data_viz_low
```




```{r message = FALSE}

graph.it <- function(df, col_order, title_phrase) {
  ggplot(df, aes(x = reorder(STATION, col_order), y = Total_Traffic)) +
  geom_bar(stat = "identity", fill = "navy", width = .5) +
  geom_text(aes(label = Total_Traffic),
            position = position_dodge(width = 0.1), hjust = -0.03, vjust = 0.5, size = 2.5) +
  coord_flip() +
  scale_y_continuous(labels = scales::comma) +
  theme(text = element_text(size = 10)) +
  labs(title = paste("20", title_phrase, "Stations for Week Ending 7/6/2018"),
       subtitle = "Total turnstile entries and exits. Data courtesty of mta.info",
       caption = "mdac",
       x = "Station",
       y = "Entries per station") 
  
}

graph.it(data_viz_hi, data_viz_hi$Total_Traffic, "Busiest")
#ggsave("total_low.png")
```

```{r}
unique(data$LINENAME)
```

```{r}
library(ggmap)
ggmap::register_google(key = "AIzaSyBGG-iWfOe7K8xqcUwcZiNRTfBiJFEt474")
```
```{r}
incidents= read.csv('https://raw.githubusercontent.com/lgellis/MiscTutorial/master/ggmap/i2Sample.csv', stringsAsFactors = FALSE)

n <- read.csv('https://raw.githubusercontent.com/lgellis/MiscTutorial/master/ggmap/n.csv', stringsAsFactors = FALSE)
```


```{r}
paste(dim(incidents), dim(n))
```


```{r}
head(incidents
     )
```


```{r}
head(n)
```


```{r}
attach(incidents)
attach(n)
```

```{r}
col1 = "#011f4b"

col2 = "#6497b1"

col3 = "#b3cde0"

col4 = "#CC0000"
```


```{r}
library(lubridate)
incidents$ymd <-mdy_hms(Event.Clearance.Date)
incidents$year <- year(incidents$ymd)

#Create a more manageable data frame with only 2017 and 2018 data
i2 <- incidents %>% 
  filter(year>=2017 & year<=2018)

#Only include complete cases
i2[complete.cases(i2), ]

#create a display label to the n data frame (dangerous neighbourhoods)
n$label <-paste(Rank, Location, sep="-")
```
```{r}
p <- ggmap(get_googlemap(center = c(lon = -122.335167, lat = 47.608013),
                    zoom = 11, scale = 2,
                    maptype ='terrain',
                    color = 'color'))
p + geom_point(aes(x = Longitude, y = Latitude,  colour = Initial.Type.Group), data = i2, size = 0.5) + 
  theme(legend.position="bottom")
```

```{r}
sbwy <- read_csv("subway_gpscoords.csv")
head(sbwy,11)
```


```{r}
options(digits = 14)

sbwy.coords <- sbwy %>% 
  mutate(
    LONG = as.numeric(str_extract(the_geom, "-\\d{2}\\.\\d+")),
    LAT = as.numeric(str_extract(the_geom, " \\d{2}\\.\\d+")))  %>%  
  rename(STATION = NAME) %>% 
  select(STATION, LONG, LAT)

sbwy.coords %>% arrange(STATION)
```


```{r}
station.gps <- merge(total.by.station, sbwy.coords)
total.by.station
```


```{r}
```



